# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RedsoTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for RedsoTest
	pod 'SwiftyJSON', '~> 4.0'
	pod 'Alamofire', '~> 5.0.0-rc.3'
	pod 'Kingfisher'
  pod "ESPullToRefresh"
  target 'RedsoTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RedsoTestUITests' do
    # Pods for testing
  end

end
